### ISSUE TITLE
For filestation API, all requests return "page not found"

### ISSUE THREAD

**Issue by jzakotnik** [satreix/synology#10]
My code used to work before (and is very similar to your example). However with the current version of synology DSM, I always receive a web page as a string:

Synology Inc
/\* Copyright (c) 2016 Synology Inc. All rights reserved. */\n\n"Sorry, the page you are looking for is not found.", (and so on)...........

 My DSM Version is DSM 6.0.1-7393 Update 1

Does it still work for you guys?

Regards Jure

**Comment by satreix** [comment]
I will look into it (I do not have a Syno at hand right now). I suspect they updated their API and moved away from the old ones.

**Comment by nicetime** [comment]
This is also my impression. If you don't manage to check it, I can also try at the weekend and figure out what is wrong. The API at least still seems available, I would guess that they updated the links, because all calls get to the same result.

**Comment by satreix** [comment]
I will look into installing DSM in a Vm if this is doable, if so I can check that out as well 😄

**Comment by nicetime** [comment]
Hi, any results on your side? I couldn't figure out so far why it's not working..

**Comment by nicetime** [comment]
HI, I fixed it locally, I think that the cgi references are not correct (anymore?). For example for download, I have to use entry.cgi.

**Comment by satreix** [comment]
I have troubles with my DSM recently so I am unable to test. Could you put together a PR?

**Comment by nicetime** [comment]
Need some time, because I didn't get through your code but simply implemented 2 http requests to get the data..

**Comment by w0ndersp00n** [comment]
It seems that all CGI Endpoints for FileStation are changed to **entry.cgi**. When replacing **FileStation/*.cgi** with **entry.cgi** the API works again.

**Comment by satreix** [comment]
@w0ndersp00n could you submit a PR please?

**Comment by satreix** [comment]
Thanks @w0ndersp00n, added this to the project in 4a51519c3377a19c3987b18ba3556641885c7780
